In [1]:
import numpy as np

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.data)

int64
2
(2, 4)
8
8


In [18]:
a=np.array([[1,2,3,4],[5,6,7,8]], dtype = float)
print(a.dtype)
print(a)

float64
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.arange(1,10,3)

array([1, 4, 7])

In [43]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [45]:
np.random.random((3,3))

array([[0.94654721, 0.91516275, 0.76227972],
       [0.03513693, 0.18138559, 0.37698879],
       [0.65161678, 0.52201209, 0.52729987]])

In [57]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [61]:
b=np.array([[1,1,1,1],[2,2,2,2]])

c=np.vstack((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [62]:
d=np.hstack((a,b))
d

array([[1, 2, 3, 4, 1, 1, 1, 1],
       [5, 6, 7, 8, 2, 2, 2, 2]])

In [71]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 1, 1, 1],
        [2, 2, 2, 2]])]

In [77]:
np.hsplit(d,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 1, 1, 1],
        [2, 2, 2, 2]])]

In [80]:
np.hsplit(c,2)

[array([[1, 2],
        [5, 6],
        [1, 1],
        [2, 2]]),
 array([[3, 4],
        [7, 8],
        [1, 1],
        [2, 2]])]